### ISSUE TITLE
After [20] retries LDAP is still dead :(

### ISSUE THREAD

**Issue by michidk** [EugenMayer/apacheds-build#2]
I'm trying to run this image on kubernetes. The image stops eventually, because netstat doesn't list the port.
I found out that apacheds can't find the config file:
```
[root@apacheds-7f688b48fc-l5jbk bin]# ./apacheds start default
Starting ApacheDS - default...
ApacheDS - default is already running.
[root@apacheds-7f688b48fc-l5jbk bin]# ./apacheds start status 
Starting ApacheDS - status...
FATAL  | wrapper  | Unable to resolve the full path of the configuration file, /var/lib/apacheds-2.0.0_M23/status/conf/wrapper-instance.conf: No such file or directory
```

How do i fix that?

**Comment by michidk** [comment]
Nevermind, i didn't specify the instance when using the status command, now it returns that the instance is running:
`ApacheDS - default is running (94).`

Problem is, that i still get the error: `TROUBLE!!! After [20] retries LDAP is still dead :(`

Logs:
```
[root@apacheds-7f688b48fc-fbh2n log]# tail -n 1000 wrapper.log  
STATUS | wrapper  | 2018/10/10 13:42:43 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2018/10/10 13:42:43 | Launching a JVM...
INFO   | jvm 1    | 2018/10/10 13:42:43 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2018/10/10 13:42:43 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2018/10/10 13:42:43 | 
INFO   | jvm 1    | 2018/10/10 13:42:44 | Trying to repair the following data :/var/lib/apacheds-2.0.0_M23/default
INFO   | jvm 1    | 2018/10/10 13:42:44 | Starting the service.
[root@apacheds-7f688b48fc-fbh2n log]# tail -n 1000 apacheds.log 
[root@apacheds-7f688b48fc-fbh2n log]# 
```

This is my kubernetes deployment (but this really shouldn't be the problem here):
https://gist.github.com/michidk/baa819cd8adc44f8a4f937c52ca2716b

Everything seems to work fine. Are there other logs, to investigate further?

**Comment by EugenMayer** [comment]
sorry i am not support apache DS any longer and wont be able to help you. Feel free to provide PRs to improve, but do not expect me to do any work for now. I am using openldap

**Comment by michidk** [comment]
yeah, already working on a PR. Do you have a similar dockerfile for openldap, which automatically installs the keybundle/certs? Always had problems, getting OpenLdap to work with TSL with letsencrypt certificates.

**Comment by EugenMayer** [comment]
I think those here will explain a lot

apacheds: https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/apacheds-ldap/3/docker-compose.yml

openldap: https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/openldap/16/docker-compose.yml

As you see i am not build openldap myself but use osixia/openldap https://github.com/osixia/docker-openldap

The main reason to not use apachds is simply, it has no memberof support as virtual attribute - absolutely deal breaker
